engines:
# to turn on an engine, add it here and set enabled to `true`
# to turn off an engine, set enabled to `false` or remove it
  eslint:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
